/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_it4y_jni_tproxy */

#ifndef _Included_org_it4y_jni_tproxy
#define _Included_org_it4y_jni_tproxy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_it4y_jni_tproxy
 * Method:    setIPTransparant
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_it4y_jni_tproxy_setIPTransparant
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_it4y_jni_tproxy
 * Method:    getOriginalDestination
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_it4y_jni_tproxy_getOriginalDestination
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
