/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_it4y_net_tuntap_TunTapLinux */

#ifndef _Included_org_it4y_net_tuntap_TunTapLinux
#define _Included_org_it4y_net_tuntap_TunTapLinux
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_it4y_net_tuntap_TunTapLinux
 * Method:    openTunDevice
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_it4y_net_tuntap_TunTapLinux_openTunDevice
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_it4y_net_tuntap_TunTapLinux
 * Method:    openTun
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_it4y_net_tuntap_TunTapLinux_openTun
  (JNIEnv *, jobject);

/*
 * Class:     org_it4y_net_tuntap_TunTapLinux
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_it4y_net_tuntap_TunTapLinux_close
  (JNIEnv *, jobject);

/*
 * Class:     org_it4y_net_tuntap_TunTapLinux
 * Method:    write
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_org_it4y_net_tuntap_TunTapLinux_write
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     org_it4y_net_tuntap_TunTapLinux
 * Method:    writeByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_it4y_net_tuntap_TunTapLinux_writeByteBuffer
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     org_it4y_net_tuntap_TunTapLinux
 * Method:    read
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_it4y_net_tuntap_TunTapLinux_read
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_it4y_net_tuntap_TunTapLinux
 * Method:    readByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_it4y_net_tuntap_TunTapLinux_readByteBuffer
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
