/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_it4y_jni_libnetlink3 */

#ifndef _Included_org_it4y_jni_libnetlink3
#define _Included_org_it4y_jni_libnetlink3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_it4y_jni_libnetlink3
 * Method:    rtnl_open
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_org_it4y_jni_libnetlink3_rtnl_1open
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     org_it4y_jni_libnetlink3
 * Method:    rtnl_open_byproto
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_org_it4y_jni_libnetlink3_rtnl_1open_1byproto
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     org_it4y_jni_libnetlink3
 * Method:    rtnl_close
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_org_it4y_jni_libnetlink3_rtnl_1close
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_it4y_jni_libnetlink3
 * Method:    rtnl_wilddump_request
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_org_it4y_jni_libnetlink3_rtnl_1wilddump_1request
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     org_it4y_jni_libnetlink3
 * Method:    rtnl_send
 * Signature: ([BLjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_it4y_jni_libnetlink3_rtnl_1send
  (JNIEnv *, jclass, jbyteArray, jobject, jint);

/*
 * Class:     org_it4y_jni_libnetlink3
 * Method:    rtnl_dump_request
 * Signature: ([BILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_it4y_jni_libnetlink3_rtnl_1dump_1request
  (JNIEnv *, jclass, jbyteArray, jint, jobject, jint);

/*
 * Class:     org_it4y_jni_libnetlink3
 * Method:    rtnl_listen
 * Signature: ([BLjava/nio/ByteBuffer;Lorg/it4y/jni/libnetlink3/rtnl_accept;)I
 */
JNIEXPORT jint JNICALL Java_org_it4y_jni_libnetlink3_rtnl_1listen
  (JNIEnv *, jclass, jbyteArray, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
