/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_it4y_jni_tuntap */

#ifndef _Included_org_it4y_jni_tuntap
#define _Included_org_it4y_jni_tuntap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_it4y_jni_tuntap
 * Method:    openTunDevice
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_it4y_jni_tuntap_openTunDevice
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_it4y_jni_tuntap
 * Method:    openTun
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_it4y_jni_tuntap_openTun
  (JNIEnv *, jobject);

/*
 * Class:     org_it4y_jni_tuntap
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_it4y_jni_tuntap_close
  (JNIEnv *, jobject);

/*
 * Class:     org_it4y_jni_tuntap
 * Method:    write
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_org_it4y_jni_tuntap_write
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     org_it4y_jni_tuntap
 * Method:    writeByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_it4y_jni_tuntap_writeByteBuffer
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     org_it4y_jni_tuntap
 * Method:    read
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_org_it4y_jni_tuntap_read
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_it4y_jni_tuntap
 * Method:    readByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_it4y_jni_tuntap_readByteBuffer
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
