/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_it4y_net_TProxyServerSocket */

#ifndef _Included_org_it4y_net_TProxyServerSocket
#define _Included_org_it4y_net_TProxyServerSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_it4y_net_TProxyServerSocket
 * Method:    setIPTransparant
 * Signature: (Ljava/net/SocketImpl;)V
 */
JNIEXPORT jint JNICALL Java_org_it4y_net_TProxyServerSocket_setIPTransparant (JNIEnv *, jobject, jint);

JNIEXPORT jint JNICALL Java_org_it4y_net_TProxyServerSocket_getOriginalDestination(JNIEnv *, jobject , jint);

#ifdef __cplusplus
}
#endif
#endif
